export const GET_WATCHES_DATA_REQUEST = "GET_WATCHES_DATA_REQUEST";
export const GET_WATCHES_DATA_SUCCESS = "GET_WATCHES_DATA_SUCCESS";
export const GET_WATCHES_DATA_FAILURE = "GET_WATCHES_DATA_FAILURE";
