export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_SUCCESS = "GET_TASKS_SUCCESS";
export const GET_TASKS_FAILURE = "GET_TASKS_FAILURE";

export const GET_TAG_REQUEST = "GET_TAG_REQUEST";
export const GET_TAG_SUCCESS = "GET_TAG_SUCCESS";
export const GET_TAG_FAILURE = "GET_TAG_FAILURE";

export const UPDATE_SUBTASKS_REQUEST = "UPDATE_SUBTASKS_REQUEST";
export const UPDATE_SUBTASKS_SUCCESS = "UPDATE_SUBTASKS_SUCCESS";
export const UPDATE_SUBTASKS_FAILURE = "UPDATE_SUBTASKS_FAILURE";
